# Meta options
# [string] @name        : Name of the game, default: name of the directory
# [string] @author      : Author of the game
# [string] @description : Description of the game
# [string] @version     : Version of the game in {major}.{minor}.{revision} format
[meta]
name        = "DDLC-LOVE"
author      = "LukeeGD"
description = "An unofficial DDLC port for the Switch!"
version     = "1.1.9"

# Build options
# [false/string]       @icon_file        : Icon to use. Do not provide the extension.
#                                    lovebrew will automatically provide this.
#                                    It can include a prepended path. This is relative
#                                    to the config file.
#
# [string]       @source_directory : Game source directory; relative to the config
#                                    file, default: "game".
#
# [false/string] @build_directory  : Output directory for compilation; relative to the config
#                                    file. When false, it will use current dir, default: false
#
# [false/string] @love_directory   : Where lovebrew looks for LÃ¶ve Potion binaries
#                                    relative to the config file, default: false.
#
# [array]        @targts           : Target console(s) to build for, default: ["3ds", "switch"]
# [bool]         @output_to_build  : When set to true, will output artifacts to the @build_directory
[build]
icon_file        = "icon"
source_directory = "game"
build_directory  = false
love_directory   = false
targets          = ["switch"]
output_to_build  = false
